USE [CamSafeDB]
/****** Object:  Table [dbo].[Cameras]    Script Date: 26/03/2024 22:01:38 ******/
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [dbo].[Cameras](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[NAME] [varchar](255) NULL,
	[IP] [varchar](32) NULL,
	[IS_ENABLED] [varchar](5) NULL,
	[CUSTOMER_ID] [int] NULL,
PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
/****** Object:  Table [dbo].[Customers]    Script Date: 26/03/2024 22:01:38 ******/
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [dbo].[Customers](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[NAME] [varchar](255) NULL,
PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
/****** Object:  Table [dbo].[Reports]    Script Date: 26/03/2024 22:01:38 ******/
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [dbo].[Reports](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[OCCURRED_AT] [varchar](26) NULL,
	[CAMERA_ID] [int] NULL,
PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
ALTER TABLE [dbo].[Cameras]  WITH CHECK ADD  CONSTRAINT [FK_Cameras_Customers] FOREIGN KEY([CUSTOMER_ID])
REFERENCES [dbo].[Customers] ([ID])
ALTER TABLE [dbo].[Cameras] CHECK CONSTRAINT [FK_Cameras_Customers]
ALTER TABLE [dbo].[Reports]  WITH CHECK ADD  CONSTRAINT [FK_Reports_Cameras] FOREIGN KEY([CAMERA_ID])
REFERENCES [dbo].[Cameras] ([ID])
ALTER TABLE [dbo].[Reports] CHECK CONSTRAINT [FK_Reports_Cameras]
ALTER TABLE [dbo].[Cameras]  WITH CHECK ADD CHECK  (([IS_ENABLED]='false' OR [IS_ENABLED]='true'))
